### ISSUE TITLE
kiwix-serve should inform the user which zim file/website their search result came from

### ISSUE THREAD

**Issue by SoopaKhell** [kiwix/kiwix-tools#478] opened 2021-08-21 17:17 UTC
Currently, the web server displays search results in a very ambiguous way:

![image](https://user-images.githubusercontent.com/11081492/130329830-421c44a0-7faf-4590-a7aa-d2efe909f026.png)

There is no way to differentiate the results, or to tell what type of content one would get if they were to click each of them. It would be nice if there was a way to have kiwix-serve display the name of the site each result comes from.

**Comment by kelson42** [comment] 2021-08-21 19:29
@SoopaKhell which zim file is that?

**Comment by SoopaKhell** [comment] 2021-08-21 19:46
> @SoopaKhell which zim file is that?

I believe the first two are the Philosophy Stack Exchange file from Kiwix.

**Comment by kelson42** [comment] 2021-08-22 05:24
This concerns the multizim search which was available via the kiwix serve homepage. This has been deactivated temproraly as long as we don't have found a solution to that problem.

On e we will be so far, we could think about that problem. Adding a small icon (zim icon) before each result woukd maybe be good enough?

**Comment by SoopaKhell** [comment] 2021-08-23 19:44
@kelson42 Yes, that would definitely go a long way.

**Comment by kelson42** [comment] 2022-01-09 17:03
Depends on https://github.com/kiwix/kiwix-tools/issues/478

**Comment by kelson42** [comment] 2022-02-11 20:47
Duplicate of https://github.com/kiwix/libkiwix/issues/704

**Closed by kelson42** 2022-02-11 20:47 UTC
Labels: duplicate, enhancement, kiwix-serve, search
