### ISSUE TITLE
kiwix-serve showing broken images

### ISSUE THREAD

**Issue by metal450** [kiwix/kiwix-tools#340] opened 2019-10-05 01:44 UTC
kiwix-serve is showing broken images for many articles, which work properly in Kiwix Desktop, Kiwix Android, etc.

Repro:
1) Download the latest Kiwix Desktop for Windows (kiwix-desktop_windows_x64_2.0-rc3 at the time of writing).
2) Download wikivoyage_en_all_maxi_2019-10.zim from https://wiki.kiwix.org/wiki/Content_in_all_languages
3) Launch Kiwix Desktop. File->Open file->select the zim.
4) Search for Osaka/Kita.  Note that the article & images work.  Screenshot: https://lnk2.tk/snaps/2019-10-04_18.41.56.png
5) Local Kiwix Server->Start Kiwix Server->Open in browser.
6) First, try just viewing the main Osaka article.  Note that images work.  Screenshot: https://lnk2.tk/snaps/2019-10-04_18.42.27.png
7) Now try Osaka/Kita.  Images are broken.  Screenshot: https://lnk2.tk/snaps/2019-10-04_18.42.53.png

**Comment by kelson42** [comment] 2019-10-05 08:36
Strange, works fine online http://library.kiwix.org/wikivoyage_en_all_maxi/A/Osaka/Kita

**Comment by kelson42** [comment] 2019-10-06 07:49
@metal450 Thank you for reporting this, the problem is with the ZIM file itself I guess. The bug is tracked here https://github.com/openzim/mwoffliner/issues/726

**Comment by kelson42** [comment] 2019-10-06 17:21
I will close this ticket as this is basically a duplicate but thx again for reporting.

**Closed by kelson42** 2019-10-06 17:21 UTC
Labels: bug, question

**Comment by metal450** [comment] 2020-05-11 21:29
I don't think this should be closed.

You mention it's the zim file itself, but the same zim works perfectly in Kiwix Desktop for Windows, and Kiwix 0.9, and Kiwix Android.  Above was just one example of the issue for the purpose of being able to reproduce it - but I have many zims and I can use all of them on all other clients; they only fail on kiwix-serve.  This includes zims I've built myself by other means (i.e. https://github.com/vss-devel/zimmer).

I was attempting to move from Kiwix 0.9 to kiwix-serve, but couldn't because kiwix-serve fails on the majority of my library.  So even if there's an issue in mwofflin, I don't think this is a duplicate. It seems like kiwix-serve should be able to handle the data that's handled by all the other clients.

**Comment by kelson42** [comment] 2020-05-11 21:34
@metal450 I'm happy to reopen the ticket if we have a recent file (`wikivoyage_en_all_maxi_2019-10.zim` is not online anymore) with a concrete article with a concrete image which works on Kiwix-Desktop and not on Kiwix-serve.

**Comment by metal450** [comment] 2020-05-11 22:31
Wait, actually, apologies - I take that back.  It looks like if I re-download newer version of all the zims that are available online, they do work; the ones that don't (i.e. that work in 0.9 & Android, but not in kiwix-serve) also don't work in Desktop, & those are only the ones that were generated by zimmer.  So I stand corrected, looks like this issue is indeed fixed - the pending one is still #270 :)
