### ISSUE TITLE
Fix kiwix-serve fulltext result page template wording (english)

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#27] opened 2017-05-01 13:31 UTC
No result were found for XXX should read

No results were found for XXX

**Comment by kelson42** [comment] 2017-05-01 13:56
@tim-moody Can you please make a detailed bug reports with all the details needed to reproduce the problem?

**Comment by tim-moody** [comment] 2017-05-01 14:08
easy. enter any search argument that returns no results and look at the message.

**Comment by kelson42** [comment] 2017-05-01 14:11
Which ZIM file?
Which version of kiwix-serve?
What is the string you exactly enter?
What do you get exactly?
What do you expect and why?

**Comment by tim-moody** [comment] 2017-05-01 14:23
1. download and untar http://download.kiwix.org/nightly/2017-04-30/kiwix-tools_armhf_2017-04-30.tar.gz
2. run  /opt/schoolserver/kiwix/bin/kiwix-serve --port 3000 /library/zims/content/wikipedia_en_medicine_2017-04.zim
3. navigate browser to <host>:3000
4. open medical wiki by clicking appropriately
5. enter XXXXXXX in search field
6. click on containing 'XXXXXXX'
7A. screen displays No result were found for XXXXXXX
7B. screen should display No results were found for XXXXXXX
The reason I expect this is because English has agreement between subject and verb with respect to number and the plural is idiomatically correct.

**Comment by tim-moody** [comment] 2017-05-01 14:25
I see that this bug existed in prior versions

**Comment by kelson42** [comment] 2017-05-01 17:10
This is a bit less trivial as it looks like because of 2d29753271123d9dc670d96306e192e11c860853. The point is that is looks like we can not change it easily now, @rgaudin you confirm? I'm not sure what would be the best approach. now. @mgautierfr Any ideas?

**Comment by rgaudin** [comment] 2017-05-01 17:36
@kelson42, can you add a link to that commit?

Last time I looked at that code (2years?), it was an English-only template [results.tmpl](https://github.com/kiwix/kiwix/blob/master/static/results.tmpl#L98) which could be easily fixed but maybe search (and its results) have moved to kiwix-lib now?

**Comment by kelson42** [comment] 2017-05-02 04:20
@rgaudin It's still english-only, but how to generate the results.ct2 file?

**Comment by mgautierfr** [comment] 2017-05-02 08:55
It seems that the ct2 file is generated by ctpp2c binary coming from ctpp2 dependency.


The results.ct2 is stored in the kiwix-lib repository (it's the searcher from kiwix-lib who use it).
We should store the results.tmpl in the repository and make the build system automatically generate the results.ct2.

**Comment by tim-moody** [comment] 2017-05-30 14:41
this remains in nightly 5-29

**Comment by kelson42** [comment] 2017-06-06 12:05
We need to fix this first https://github.com/kiwix/kiwix-lib/issues/50

**Comment by kelson42** [comment] 2017-07-19 19:49
Fixed with https://github.com/kiwix/kiwix-lib/pull/68/commits/b6a58d1684037d0575caddeafe1252af455a2c21

**Closed by kelson42** 2017-07-19 19:49 UTC
Labels: bug
