### ISSUE TITLE
Search Feature for Library Crashes

### ISSUE THREAD

**Issue by ISJ-439** [kiwix/kiwix-tools#528] opened 2022-01-31 05:05 UTC
**Situation:** I have 16 versions of Wikipedia, one for each year, and some for the same year and just different quarters.
**Current Result:** On the main library page I search for "Apples" an it crashes the entire process.
**Expected Result:** It would search as normal.

**Note:** The system is under powered (older CPU and non SSD) but this is only 1 search and not a heavy load.

How would I collect better logging on this issue to help you assist with fixing the issues present?

**Comment by kelson42** [comment] 2022-01-31 05:36
I confirm the problem with multizim search. This ticket is basically a duplicate of https://github.com/kiwix/libkiwix/issues/479. It is at the very top of our priority list for libkiwix.

**Closed** 2022-01-31 05:37 UTC
Labels: bug, duplicate, question, search
