### ISSUE TITLE
Move to/Support another Docker registry other than Docker Hub

### ISSUE THREAD

**Issue by jacroe** [kiwix/kiwix-tools#606] opened 2023-03-15 23:03 UTC
Based on the issues described in [this blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/), Docker Hub is, perhaps, no longer a safe provider of Docker images. Unless the project is willing to pay.

What I would like is for the project to support a different Docker registry, in combination or not, with [GHCR.io](https://ghcr.io/) or [Quay](https://quay.io/).

Quite a bit of additional context can be seen in [Hacker News](https://news.ycombinator.com/item?id=35166317) and this [/r/selfhosted post](https://www.reddit.com/r/selfhosted/comments/11ryub1/fyi_docker_is_deleting_open_source_organisations/).

**Comment by kelson42** [comment] 2023-03-16 05:18
@jacroe Is not that clear so far. We will wait to know more.

**Comment by kelson42** [comment] 2023-03-20 07:52
@jacroe Seems the news is confirmed, we will do the necessary

**Comment by mgautierfr** [comment] 2023-03-20 09:12
Do we have a `Docker Free Team` account ? Because if we don't, we are not impacted. (https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)

**Comment by kelson42** [comment] 2023-03-23 06:46
Fixed with #608

**Closed by kelson42** 2023-03-23 06:46 UTC
Labels: task
