### ISSUE TITLE
Kiwix-serve fails to find in-zim full text index

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-tools#198] opened 2018-06-01 08:37 UTC
kiwix-serve 0.5 fails to find the full text index inside ZIM files when not launched in `--library` mode.

**Note**: working properly with kiwix-tools nightly `2018-05-31`.

**Kiwix-serve 0.5**
![ss-kiwix-serve_0 5](https://user-images.githubusercontent.com/57929/40830670-907ba5ec-6576-11e8-8c51-33d3aa352f89.png)

**Kiwix-serve nightly**
![ss-kiwix-serve_nightly](https://user-images.githubusercontent.com/57929/40830669-90480d54-6576-11e8-9e8d-8c9372460ac5.png)

**Comment by kelson42** [comment] 2018-06-01 09:41
Quite sure a duplicate of #193

**Closed by kelson42** 2018-06-01 09:41 UTC
Labels: bug, kiwix-serve
