### ISSUE TITLE
library_zim.xml has bad data

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#120] opened 2017-12-01 22:25 UTC
book id="d5ac404a-422b-092a-5899-cdeb151de191" title="WikiMed mini" name="kiwix.wikipedia_en_medicine" tags=""nopic;nodet";_ftindex"

has spurious quotes in tags

**Comment by mgautierfr** [comment] 2017-12-01 22:38
Duplicate of https://github.com/openzim/mwoffliner/issues/134

**Closed by mgautierfr** 2017-12-01 22:38 UTC
