### ISSUE TITLE
partial word searches like "pneumoni" can crash kiwix-serve (e.g. try a medical ZIM)

### ISSUE THREAD

**Issue by holta** [kiwix/kiwix-tools#155] opened 2018-02-19 16:30 UTC
@tim-moody can reproduce this consistently but intermittently using ZIM http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2018-01.zim

It's hard to reproduce every time.  So other Internet-in-a-Box people will continue to document this here as we learn more: https://github.com/iiab/iiab/issues/684

As a result we're also looking at forcibly restarting kiwix-serve upon detection of this and similar problems &mdash; using MySQL and add a restart &mdash; something like the following possibly:
```# Restart crashed server only, on-failure would also restart, for example, when
# my.cnf contains unknown option
Restart=on-abort
RestartSec=5s
```

**Comment by kelson42** [comment] 2018-02-19 20:12
@holta Thx, yes we definitly still have at least one scenario related to the search. This ticket might be a duplicate of #153

**Comment by kelson42** [comment] 2018-02-19 20:13
I have the problem on http://library.kiwix.org. I just have put the whole in a `while [ 42 ]` bash loop.

**Comment by tim-moody** [comment] 2018-02-19 23:16
It is strange that after some time these searches work, even on reboot. Is there a permanent buffer created for the index or some other file?

**Comment by mgautierfr** [comment] 2018-02-22 14:08
You are testing with a kiwix-serve from 2017-12-27. Since, I have fixed the issue https://github.com/kiwix/kiwix-tools/issues/119
It was due to not initialized value. It could explain the randomness of the crash.

It is possible to have a log of the crash ?
Can you test with a more recent version on kiwix-serve ?
On my side I cannot reproduce with a recent kiwix-serve, but it may be just because I cannot reproduce, not because it is fixed. (log could help to know if it is the same issue)

**Comment by tim-moody** [comment] 2018-02-22 14:18
@mgautierfr which version should I use? I agree it is difficult to reproduce as it happens initially and then stops. I'm not sure where the log is.

**Comment by mgautierfr** [comment] 2018-02-22 18:37
@tim-moody Any version after 2019-01-09 when the fix were included.

You can also wait for the tomorrow version who will included this fix https://github.com/openzim/libzim/pull/117 that should greatly improve suggestion results (but not fix any crash).

**Comment by holta** [comment] 2018-02-22 19:39
> wait for the tomorrow version

Will do thx!

> Any version after 2019-01-09

Even better any 2020 software you have handy (not just 2019 ;)

**Comment by mgautierfr** [comment] 2018-02-23 09:39
> Even better any 2020 software you have handy (not just 2019 ;)

Haha I'm pretty sure that 2019-01-09 version will have this issue fixed :)
(And it was of course 2018-01-09)

**Comment by kelson42** [comment] 2018-02-26 19:22
Bug seems to be fixed

**Closed by kelson42** 2018-02-26 19:22 UTC
Labels: bug
