### ISSUE TITLE
Kiwix-serve aborting on certain pages

### ISSUE THREAD

**Issue by nicholasmorrissey** [kiwix/kiwix-tools#388] opened 2020-06-16 07:53 UTC
Hey guys,

I am working on an offline system and have to manually copy over the information, so forgive me that I can't give the entire stack trace, but I'm hoping you have some insight into this problem as I can't find it anywhere else.

I've recently downloaded the kiwix-tools_linux-x86-3.1.1-3 set of binaries and have been trying to run kiwix-serve with a wikipedia_en_100_nopic_2020-05.zim file to test it. It does work fine for most wiki pages, but when I open certain pages (often country pages if that helps) it makes 2-3 supposedly successful requests for css modules that look like:
/css_modules/mw.MediaWikiPlayer.loader.css
/css_modules/mw.PopUpMediaTransform.css
/css_modules/mw.TMHGalleryHook.js.css

and then gives this failed assertion:

kiwix-serve: ../..SOURCE/kiwix-lib_release/src/server/byte_range.cpp:68: kiwix:: ByteRange::ByteRange(kiwix::ByteRange::Kind, int64_t, int64_t): Assertion 'last >= first' failed.
Aborted.

I'm going to try with a different zim file soon but it's gonna take a bit to get it across.

Do you have any idea what's causing this? Also I am solely running it off the pre-compiled kiwix-serve binary in kiwix-tools, am I right in assuming I don't need to set up the extra dependencies/environment tools such as Meson, Ninja, and pkg-config for this case since it's pre-compiled?

**Comment by veloman-yunkan** [comment] 2020-06-16 10:04
This should be fixed with kiwix/kiwix-lib#364

**Closed by veloman-yunkan** 2020-06-16 10:04 UTC

**Comment by veloman-yunkan** [comment] 2020-06-16 10:06
Duplicate of kiwix/kiwix-lib#363

**Comment by nicholasmorrissey** [comment] 2020-06-17 00:44
Sorry that I didn't see that, but thanks for the timely response. Was the fix brought in with the kiwix-tools_linux-3.1.1-4 version? Or is it yet to come?

**Comment by kelson42** [comment] 2020-06-17 06:10
Yes, this is already released.
