### ISSUE TITLE
kiwix-serve becomes unresponsive on Raspberry Pi

### ISSUE THREAD

**Issue by mrcage** [kiwix/kiwix-tools#452] opened 2021-04-15 17:27 UTC
## Transfer comment

Originally opened on kiwix-hotspot. It appears that kiwix-serve with a large number of zim files (passed in command-line, not inside a library) is using tons of CPU avec a couple of minutes and then becomes unresponsive.

That happens on RasPi 3B+ and Raspi 4B – on arm

## Original comment

I am experiencing issues with Kiwix Hotspot images on Raspberry Pi (Model 4B and 3B+ tested so far using Samsung microSD cards). Whenever I flash a micro SD card, put it into the Raspberry, start it up and access the Kiwix Hotspot web page. everything works fine for a few minutes, but after that all ZIM-based content (Wikipedias etc) become non-responsive. I can click on any link on the start page, and the browser just tries to load the site for an indefinite period of time. Khan Academy still works. I currently have no way to debug it, as SS access seems to be disabled, and there is no admin mode (even though I set an admin name and password in the Hotspot generator, this is probably a separate issue). I tried both with an image created using the hotspot installer, and an image created using your card shop, as I was suspecting there might be something wrong with the hotspot installer. 

I've also tried several different SD cards from various brands, the issue persists. FYI my image is more than 200GB, I've also tried with a 100GB-ish image before. SSH to the raspberry Pi does not work, and there is no admin panel available in Kiwix (although the images were created with an admin user and password set). 

It seems to be related to the Kiwix Software itself which runs on port 8002. KA Lite which runs on port 8008 is still working fine, but any HTTP request to port 8002 takes indefinitely.

**Comment by Popolechien** [comment] 2021-04-16 07:50
@rgaudin I think it was this order https://cardshop.hotspot.kiwix.org/all-orders/607415e998c8bf00236bb163

**Comment by rgaudin** [comment] 2021-04-16 07:50
Thanks ; the command line is above, the list of packages is there

**Comment by mrcage** [comment] 2021-04-16 07:51
From /data/packages:

aimhi_english.en.zim
aimhi_geography.en.zim
christianity.stackexchange.com_en_all.en.zim
covid19relay_en_all_maxi.en.zim
education-et-numerique_fr_all.fr.zim
ekopedia_fr_all.fr.zim
gutenberg_ar_all.ar.zim
gutenberg_fa_all.fa.zim
gutenberg_fr_all.fr.zim
islam.stackexchange.com_en_all.en.zim
jaimelire_fr.fr.zim
khan-academy-videos_fr_bases-de-la-geometrie.fr.zim
khan-academy-videos_fr_bases-de-l-algebre.fr.zim
khan-academy-videos_fr_l-ecologie.fr.zim
khan-academy-videos_fr_les-systemes-du-corps-humain.fr.zim
khan-academy-videos_fr_sante-et-medecine.fr.zim
khan-academy-videos_tr_bilgisayar-proglamlama-bilgisayar-dunyasi.tr.zim
khan-academy-videos_tr_elektrik-muhendisligi-fen-bilimleri.tr.zim
khan-academy-videos_tr_felsefe-sanat-ve-sosyal-bilimler.tr.zim
khan-academy-videos_tr_isik-ve-renkler.tr.zim
khan-academy-videos_tr_kimya-hizlandirilmis-kurs-crash-course.tr.zim
khan-academy-videos_tr_lineer-cebir-vektorler-uzay-ve-matris-donusumleri.tr.zim
khan-academy-videos_tr_mikroekonomi-ekonomi-ve-finans.tr.zim
khan-academy-videos_tr_muzik-sosyal-bilimler-ve-sanat.tr.zim
lifehacks.stackexchange.com_en_all.en.zim
phzh_core-arabic-one-test-zim_ar.en.zim
phzh_core-english-one_en.en.zim
phzh_core-greek-one_el.en.zim
poesies_fr.fr.zim
ted_en_playlist-10-talks-by-women-that-everyon.en.zim
ted_en_playlist-11-must-see-ted-talks.en.zim
ted_en_playlist-how-to-invest-in-social-good.en.zim
ted_en_playlist-immigrants-who-founded-amazing-companies.en.zim
ted_en_playlist-kickstart-your-creativity.en.zim
ted_en_playlist-music-around-the-world.en.zim
ted_en_playlist-natural-wonder.en.zim
ted_en_playlist-powerful-art-activism.en.zim
ted_en_playlist-powerful-poetry-by-fierce-women.en.zim
ted_en_playlist-talks-that-explain-difficult-t.en.zim
ted_en_playlist-talks-to-restore-your-faith-in-1.en.zim
ted_en_playlist-talks-to-watch-when-you-have-a.en.zim
ted_en_playlist-ted-talks-by-strong-women-lead.en.zim
ted_en_playlist-the-10-most-popular-tedx-talks.en.zim
ted_en_playlist-the-beauty-of-strangers.en.zim
ted_en_playlist-the-future-of-medicine.en.zim
ted_en_playlist-the-love-of-lifelong-learning.en.zim
ted_en_playlist-the-most-popular-talks-of-2019.en.zim
ted_en_playlist-the-path-to-reconciliation.en.zim
ted_en_playlist-the-power-of-fiction-1.en.zim
ted_en_playlist-the-power-of-protest.en.zim
ted_en_playlist-the-power-of-social-media.en.zim
ted_en_playlist-the-rise-of-africa-s-next-gene.en.zim
ted_en_playlist-the-road-to-peace.en.zim
ted_en_playlist-virtuosos.en.zim
ted_en_playlist-what-comes-after-war.en.zim
ted_en_playlist-what-does-the-future-look-like.en.zim
ted_en_playlist-what-is-home.en.zim
ted_en_playlist-what-makes-you-happy.en.zim
ted_en_playlist-what-you-need-to-know-about-me.en.zim
ted_en_playlist-what-your-data-reveals-about-y.en.zim
ted_en_playlist-when-your-beliefs-are-being-ch.en.zim
ted_en_playlist-where-do-ideas-come-from.en.zim
ted_en_playlist-why-climate-change-is-a-human.en.zim
ted_en_playlist-why-do-we-tell-stories.en.zim
ted_en_playlist-why-we-need-brave-journalists.en.zim
wikem_en_all_maxi.en.zim
wikipedia_ar_all_maxi.ar.zim
wikipedia_ar_chemistry_maxi.ar.zim
wikipedia_ar_computer_maxi.ar.zim
wikipedia_ar_football_maxi.ar.zim
wikipedia_ar_geography_maxi.ar.zim
wikipedia_ar_history_maxi.ar.zim
wikipedia_ar_mathematics_maxi.ar.zim
wikipedia_ar_medicine_nopic.ar.zim
wikipedia_ar_molcell_maxi.ar.zim
wikipedia_ar_movies_maxi.ar.zim
wikipedia_ar_physics_maxi.ar.zim
wikipedia_en_100.en.zim
wikipedia_en_astronomy_maxi.en.zim
wikipedia_en_chemistry_maxi.en.zim
wikipedia_en_climate_change_maxi.en.zim
wikipedia_en_computer_maxi.en.zim
wikipedia_en_football_maxi.en.zim
wikipedia_en_for-schools.en.zim
wikipedia_en_geography_maxi.en.zim
wikipedia_en_history_maxi.en.zim
wikipedia_en_mathematics_maxi.en.zim
wikipedia_en_medicine.en.zim
wikipedia_en_movies_maxi.en.zim
wikipedia_en_physics_maxi.en.zim
wikipedia_en_simple_all_maxi.en.zim
wikipedia_en_sociology_maxi.en.zim
wikipedia_en_top_maxi.en.zim
wikipedia_fa_all_maxi.fa.zim
wikipedia_fa_medicine_maxi.fa.zim
wikipedia_fr_all_maxi.fr.zim
wikipedia_fr_chemistry_maxi.fr.zim
wikipedia_fr_climate_change_maxi.fr.zim
wikipedia_fr_computer_maxi.fr.zim
wikipedia_fr_football_maxi.fr.zim
wikipedia_fr_geography_maxi.fr.zim
wikipedia_fr_history_maxi.fr.zim
wikipedia_fr_mathematics_maxi.fr.zim
wikipedia_fr_movies_maxi.fr.zim
wikipedia_ku_all_maxi.ku.zim
wikipedia_ln_all_maxi.ln.zim
wikipedia_tr_all_maxi.tr.zim
wikipedia_tr_chemistry_maxi.tr.zim
wikipedia_tr_computer_maxi.tr.zim
wikipedia_tr_football_maxi.tr.zim
wikipedia_tr_geography_maxi.tr.zim
wikipedia_tr_history_maxi.tr.zim
wikipedia_tr_mathematics_maxi.tr.zim
wikipedia_tr_movies_maxi.tr.zim
wikipedia_tr_physics_maxi.tr.zim
wikipedia_ur_all_maxi.ur.zim
wikipedia_ur_medicine_maxi.ur.zim
wikivoyage_en_all_maxi.en.zim
wikivoyage_en_europe_maxi.en.zim
wikivoyage_fa_all_maxi.fa.zim
wikivoyage_fr_all_maxi.fr.zim
wiktionary_ar_all_maxi.ar.zim
youscribe_fr_primaire.fr.zim

**Comment by kelson42** [comment] 2021-04-16 07:54
@mrcage Does a special request to the ZIM makes the whole service to die? For example a search request?

**Comment by rgaudin** [comment] 2021-04-16 07:55
See #420

**Comment by mrcage** [comment] 2021-04-16 07:55
I did not do special requests, as far as I can say. I just click randomly around some of the links in the wiki, access several wikis, access several ted talk videos etc

**Comment by mrcage** [comment] 2021-04-16 08:35
One question which popped up in my mind is why not a library file is used, and this huge list of zim files gets added to the kiwix-serve command....

**Comment by kelson42** [comment] 2021-04-16 08:43
> One question which popped up in my mind is why not a library file is used, and this huge list of zim files gets added to the kiwix-serve command....

Because there is no need and loading the ZIM files directly leads to the same result from a user perspective.

**Comment by rgaudin** [comment] 2021-04-16 08:43
@mrcage would you mind testing with a library file?
You can create the library file and add your ZIM files to it with the `kiwix-library` binary that's included.

**Comment by kelson42** [comment] 2021-04-16 08:46
> See #420

Yes, pretty much a duplicate of #410 IMO

**Comment by kelson42** [comment] 2021-04-16 08:46
Might be worse to check if the bug is still in the nighly https://download.kiwix.org/nightly/2021-04-14/kiwix-tools_linux-armhf-2021-04-14.tar.gz

**Comment by mrcage** [comment] 2021-04-16 09:10
Yep, it also happens with the latest nightly build

![image](https://user-images.githubusercontent.com/1665428/115001804-ad0ff600-9eac-11eb-9865-ba9911e13940.png)

**Comment by mrcage** [comment] 2021-04-16 09:55
@rgaudin I tried with a library file, but the outcome seems to be the same.

See attached the library file [test-library.zip](https://github.com/kiwix/kiwix-tools/files/6324116/test-library.zip), which I created with

    for f in /data/packages/*.zim; do echo $f; sudo /home/pi/kiwix-tools_linux-armhf-2021-04-14/kiwix-manage /data/packages/test-library.xml add $f; done
    
and then starting the server with   

    /usr/local/bin/kiwix-serve --port=8002 --library /data/packages/test-library.xml

**Comment by rgaudin** [comment] 2021-04-16 09:57
Well it confirms what @kelson42 was suggesting. Once it's loaded, it's identical. Sorry for your time.

**Comment by mrcage** [comment] 2021-04-16 09:59
No problem. I am trying to find a pattern on when it happens. In some instances now, rapidly clicking the "random" article button in one of the wikis seem to load the content quite fast. I experienced several times a sharp rise in CPU usage when loading one of the wikis that is a sub-collection and has this large masonry-like picture overview (e.g. the football wiki) instead of the classical wiki start page....

**Comment by kelson42** [comment] 2021-04-16 12:54
@mrcage There is obviously a bug in kiwix-serve here, but the root cause is pretty unclear so far. For the moment I have only two theories:
* Kiwix Serve can serve a lot of ZIM files (like on https://library.kiwix.org/) but maybe by so many ZIM files there is a behaviour which is wrong enough to just fail with a small hardware like the RPI. It would be interesting here to reduce the number of ZIM files served and see how it behaves.
* In all these ZIM files, there one (or two) ZIM files which defenitly have somehow a problem and make the daemon fail. Just removing them from the list would solve the problem.

**Comment by threalboss** [comment] 2021-04-23 12:44
I am having this same exact problem on my pi 3b+. It is running a 32gb sd card. Would also love a to find a fix.

**Comment by kelson42** [comment] 2021-04-23 14:20
@threalboss You confirm as well that you have a lot of different ZIM files on your SD card?

**Comment by threalboss** [comment] 2021-04-24 17:23
Yes I do have a good amount of files. Probably about 30. Thanks.

**Comment by kelson42** [comment] 2021-04-26 08:24
I will close that ticket in favour of #420. Please subscribe to #420 to be kept inform about the fix.

**Closed by kelson42** 2021-04-26 08:24 UTC
Labels: bug, duplicate, kiwix-serve
