### ISSUE TITLE
path problem with kiwix-serve library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#57] opened 2017-07-23 18:48 UTC
_From @rashiq on June 8, 2016 13:4_

**Reported by kelson42 on 2014-10-31 16:27 UTC**
In certain situation, kiwix-serve seems to be unable to read the library.

kelson@camber:/tmp$ ./kiwix/bin/kiwix-serve --library wikipedia_de_all_12_2013.zim.xml 
Unable to open the XML library file 'wikipedia_de_all_12_2013.zim.xml'.

kelson@camber:/tmp/kiwix/bin$ ./kiwix-serve --library ../../wikipedia_de_all_12_2013.zim.xml 
error 2 opening file "/content/wikipedia_de_all_12_2013.zim": No such file or directory
The XML library file '../../wikipedia_de_all_12_2013.zim.xml' is empty (or has only remote books).
Unable to instanciate the HTTP daemon. The port 80 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.

_Copied from original issue: kiwix/kiwix-xulrunner#165_

**Comment by julianharty** [comment] 2017-07-24 09:33
It'd also be great to improve the diagnostic message. The second part is not relevant to the cause of the inability to start:
```
"Unable to instanciate the HTTP daemon. The port 80 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024."
```
And as a detail, there was a typo in that error message. I've edited the code and created a pull request: https://github.com/kiwix/kiwix-tools/pull/62

**Comment by mgautierfr** [comment] 2017-07-24 09:41
I know this bug is pretty old, bui it is possible to have the content of `wikipedia_de_all_12_2013.zim.xml` and the exact location of both `kiwix-serve`, `wikipedia_de_all_12_2013.zim.xml` and `wikipedia_de_all_12_2013.zim` ?

**Comment by mgautierfr** [comment] 2017-11-13 10:38
First problem is a duplicate of #70 

The second one seems a problem of path in the "xml" file itself (wrong path of the zim file)

Without further information, I'm closing it.

**Closed by mgautierfr** 2017-11-13 10:38 UTC
Labels: bug, kiwix-serve
