### ISSUE TITLE
Remove article name display from Wikipedia article

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-tools#295] opened 2019-05-24 17:03 UTC
Based on #293, if the article name is already indicated on top, is it possible to hide it from the text' body (the one that's ``<h1>`` sized)?
As a matter of fact, for Wikipedia articles I'm not even sure we _need_ to display the title as it's being repeated in bold in the leade and Wikipedians are pretty consistent with that formatting custom (not the case . Thoughts?
![5](https://user-images.githubusercontent.com/21675885/58344449-018fcf80-7e56-11e9-89d4-07c0f78cb046.jpg)

**Comment by kelson42** [comment] 2019-05-25 19:10
This is a pure duplicate of #293, I don't see any difference. This should be put as a comment for #293.

**Closed by kelson42** 2019-05-25 19:10 UTC
Labels: duplicate, enhancement
