### ISSUE TITLE
New kiwix-serve crash scenario with 2.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#299] opened 2019-06-05 15:21 UTC
Download http://tmp.kiwix.org/tutu.zim. Laund kiwix-serve, go the ZIM homepage and then just type "J" in the search bar.

The kiwix-serve crash:
```
$ kiwix-serve --verbose --port=8080 out/wikipedia_bm_all_2019-06.zim 
======================
Requesting : 
full_url  : /suggest
method    : GET (0)
version   : HTTP/1.1
headers   :
 - Accept : 'application/json, text/javascript, */*; q=0.01'
 - Accept-Encoding : 'gzip, deflate'
 - Accept-Language : 'fr,en-US;q=0.8,en;q=0.5,de;q=0.3'
 - Connection : 'keep-alive'
 - Cookie : '_ga=GA1.1.1481809055.1496164515'
 - DNT : '1'
 - Host : 'localhost:8080'
 - Referer : 'http://localhost:8080/search?content=wikipedia_bm_all_2019-06&pattern=J'
 - User-Agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0'
 - X-Requested-With : 'XMLHttpRequest'
arguments :
 - content : 'wikipedia_bm_all_2019-06'
 - term : 'k'
Parsed : 
url   : /suggest
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_suggest
Searching suggestions for: "k"
No steemming for language 'bm'
Response :
httpResponseCode : 200
headers :
 - Cache-Control: 'max-age=2723040, public'
 - Access-Control-Allow-Origin: '*'
 - Content-Type: 'application/json; charset=utf-8'
 - Accept-Ranges: 'bytes'
 - Content-Encoding: 'deflate'
 - Vary: 'Accept-Encoding'
----------------------
======================
Requesting : 
full_url  : /suggest
method    : GET (0)
version   : HTTP/1.1
headers   :
 - Accept : 'application/json, text/javascript, */*; q=0.01'
 - Accept-Encoding : 'gzip, deflate'
 - Accept-Language : 'fr,en-US;q=0.8,en;q=0.5,de;q=0.3'
 - Connection : 'keep-alive'
 - Cookie : '_ga=GA1.1.1481809055.1496164515'
 - DNT : '1'
 - Host : 'localhost:8080'
 - Referer : 'http://localhost:8080/search?content=wikipedia_bm_all_2019-06&pattern=J'
 - User-Agent : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0'
 - X-Requested-With : 'XMLHttpRequest'
arguments :
 - content : 'wikipedia_bm_all_2019-06'
 - term : 'J'
Parsed : 
url   : /suggest
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_suggest
Searching suggestions for: "J"
No steemming for language 'bm'
Segmentation fault (core dumped)
```

**Comment by jetownfeve21** [comment] 2019-06-06 11:20
It will be fixed with https://github.com/kiwix/kiwix-lib/pull/228

**Comment by mgautierfr** [comment] 2019-06-11 09:41
While I agree that kiwix-serve should not crash, the problem is that `tutu.zim` is not coherent.
A search suggestion return an article called `jara` (see `kiwix-search -s tutu.zim j`) and there is no such article in the zim file (see `zimdump -l tutu.zim`). How have you generated the zim file ?

**Comment by kelson42** [comment] 2019-06-12 05:07
@mgautierfr Agree. Created a dedicated ticket here https://github.com/openzim/libzim/issues/240

**Closed** 2019-06-24 09:54 UTC
Labels: bug, kiwix-serve
