### ISSUE TITLE
Taskbar should be customizable.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-tools#66] opened 2017-08-13 15:57 UTC
When kiwix-serve is used in another solution (ideascube for example, by BSF or pibox), the "home" page is not the kiwix-serve library but the solution homepage.

We should allow those solution to modify the taskbar to add a link (or change the library button) pointing to the "real" homepage.

This is especially needed by pibox solution. Pibox is creating a captive portal and use the captive portal page to display the home page. In most computer, this captive portal page is opened automatically in a web browser without navigation button. It's means that once a user has enter a zim file, he cannot go back to the home page at all.

**Comment by kelson42** [comment] 2017-09-10 18:22
This seems to be a duplicate of #17

**Closed by kelson42** 2017-09-10 18:22 UTC
Labels: enhancement
