### ISSUE TITLE
Kiwix Serve Unable to Stream Video Media to mobile devices

### ISSUE THREAD

**Issue by wsteven-son** [kiwix/kiwix-tools#484] opened 2021-09-24 20:07 UTC
Hello, I have Kiwix Serve running on Ubuntu. When a client attempts to play a video on a mobile device (for example Ted Talk on an Iphone/ipad) the video does not play. It appears to fully load in as still images are displayed but the video will not play. I have experience similiar issues with Jellyfin and believe this is a video transcoding issue. Are the videos transcoding by kiwix serve or is it direct play?

**Comment by kelson42** [comment] 2021-09-25 16:50
Seems a duplicate of https://github.com/openzim/youtube/issues/34

**Comment by kelson42** [comment] 2021-09-26 15:28
I confirm http://library.kiwix.org/ted_en_playlist-how-to-run-a-company-like-a-vi_2021-01/A/how-to-run-a-company-with-almost-no-rules?lang=undefined  does not play with ipados 15. Still closing because of duplication.

**Closed by kelson42** 2021-09-26 15:28 UTC
Labels: question, kiwix-serve
