### ISSUE TITLE
[Question] browser sending external requests in the background

### ISSUE THREAD

**Issue by DarkmatterUAE** [kiwix/kiwix-tools#590] opened 2022-12-18 01:54 UTC
When the browser is loading a wikipedia page from kiwix-serve, I got curious why it's taking a few seconds to complete, so I opened the dev tools, ticked "Disable cache" and reloaded the page.
Kind of curious why requests to `upload.wikimedia.org` appeared (though failed, since there's Internet censorship in my country) on the network log? Is this a problem with the zim file, or should kiwix-serve blocks such external assets loading from happening?
![Screenshot showing 3 requests to upload.wikimedia.org being made during page load](https://upload.cc/i1/2022/12/18/3CkA6M.png)

kiwix-serve in alpine linux:
```kiwix-tools 3.3.0

libkiwix 11.0.0
+ libzim 8.0.0
+ libxapian 1.4.21
+ libcurl 7.86.0
+ libmicrohttpd 0.9.75
+ libz 1.2.13
+ libicu 72.1.0
+ libpugixml 1.12.0

libzim 8.0.0
+ libzstd 1.5.2
+ liblzma 5.2.7
+ libxapian 1.4.21
+ libicu 72.1.0
```

**Comment by kelson42** [comment] 2022-12-18 08:25
This is a problem with mwoffliner and ticket shoukd be moved there... but we already one of that kind there I believe.

**Comment by nijazm** [comment] 2022-12-19 23:10
yes, I reported that few years ago, from different github account, but I block such requests locally using extensions like ublock origin or umatrix...I think only two images or svg files try to be loaded

**Comment by mgautierfr** [comment] 2022-12-20 10:36
It would be interesting to test it with kiwix-desktop. kiwix-desktop should block this kind of requests even if the zim file itself is buggy.

**Comment by DarkmatterUAE** [comment] 2022-12-23 06:36
> I think only two images or svg files try to be loaded

Yes. It's a lock-shaped indicator suggesting certain cited material can only be accessed after registration.

https://en.wikipedia.org/wiki/Template:Citation#Subscription_or_registration_required

**Comment by kelson42** [comment] 2022-12-23 13:24
Duplicate of https://github.com/openzim/mwoffliner/issues/1280

**Closed by kelson42** 2022-12-23 13:24 UTC
Labels: bug
