### ISSUE TITLE
& in the suggestions gets to &amp; in the search field

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-tools#453] opened 2021-04-16 19:18 UTC
Using kiwix-serve x86_64-3.1.2-4, wikipedia-de and Firefox I search for "Übel " and get the suggestions:

* Übel & gefährlich
* Übel Blatt
* containing 'Übel ' ...

If I click on "Übel & gefährlich" in the search field appears "Übel \&amp; gefährlich" and a full text search is done, instead of leading me to page "Übel & gefährlich".

**Comment by mgautierfr** [comment] 2021-04-19 09:30
Related to https://github.com/openzim/libzim/issues/536

@maneeshpm can you confirm this is the same issue and it is fixed ?

**Comment by maneeshpm** [comment] 2021-04-19 11:19
@mgautierfr This issue seems a bit different. We can be sure that openzim/libzim#536 is fixed since the we are getting proper suggestions. As reported, the issue occurs when we click the "containing ...string..." option. I feel this is an HTML encoding issue with the form and might be related to [this](https://github.com/kiwix/kiwix-lib/pull/464#discussion_r595951423).

**Comment by kelson42** [comment] 2021-04-19 19:41
@maneeshpm So you can reproduce the problem with developement kiwix-serve?

**Comment by maneeshpm** [comment] 2021-04-19 19:44
@kelson42 Yes, It's there in the latest kiwix-lib master.

**Comment by maneeshpm** [comment] 2021-04-20 15:49
@kelson42 I think the issue has been fixed. I tried to recreate the issue after clearing my browser cache and the issue was gone. 
@JensKorte can you confirm?

**Comment by JensKorte** [comment] 2021-04-20 17:42
@maneeshpm I am compiling all the dependencies and can't give a fast reply.

**Comment by JensKorte** [comment] 2021-04-20 19:27
@maneeshpm I guess somewhere missed to include the libs that suggestions work for me. I give up compiling it on my own. If there is a release or a rc I will try it.

**Comment by maneeshpm** [comment] 2021-04-20 20:25
Ohk @JensKorte, please keep us posted. 

@kelson42 I cannot reproduce this bug anymore, we can close this issue now.

**Closed** 2021-04-21 03:45 UTC
Labels: bug, search
