### ISSUE TITLE
New kiwix-serve "crash" scenario

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#150] opened 2018-01-22 18:09 UTC
No `core` file, but kiwix-serve exits with the following log

```
======================
Requesting :
full_url  : /wikipedia_en_wp1-0.7_2009-05/I/wikibits.js
method    : GET (0)
version   : HTTP/1.0
headers   :
 - Accept : '*/*,*/*'
 - Accept-Encoding : 'gzip,deflate,br'
 - Accept-Language : 'en-US'
 - Connection : 'close'
 - From : 'googlebot(at)googlebot.com'
 - Host : 'library.kiwix.org'
 - Referer : 'http://library.kiwix.org/wikipedia_en_wp1-0.7_2009-05/'
 - User-Agent : 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
 - X-Forwarded-For : '66.249.76.151'
 - X-Real-IP : '66.249.76.151'
arguments :
Parsed :
url   : /wikipedia_en_wp1-0.7_2009-05/I/wikibits.js
acceptEncodingDeflate : 1
has_range : 0
.............
** running handle_content
Found /I/wikibits.js
mimeType: application/javascript

Assertion failed at ../../SOURCE/libzim/src/file_reader.cpp:113
 size[18446744071263238467] <= _size[2446323373]
[0x4d9417]
[0x4ea8e7]
[0x4eb173]
[0x4eb62f]
[0x4dfe91]
[0x4d686a]
[0x4d73ef]
[0x407c3e]
[0x408efd]
[0x8474c5]
[0x848d87]
[0x84e1f9]
[0x84e57b]
[0x84ef40]
[0x840cc4]
[0x9950b9]
```

**Comment by mgautierfr** [comment] 2018-01-31 10:31
I can reproduce.

Where this zim file (wikipedia_en_wp1-0.7_2009-05) come from ? It has no checksum and as far I know, we always add a checksum to the zim file (at least since `libzimwriter` has been merged in `libzim`, in 2012).
The `2009` in the zim name make me think it a pretty old zim file.

Anyway, I still haven't investigate further to know if the zim file is corrupted somehow or if it is a bug in libzim (and in anycase, libzim should definitively not crash, even with a corrupted zim)

**Comment by mgautierfr** [comment] 2018-01-31 11:27
This was a bug in libzim.
It is fixed.

**Closed** 2018-01-31 11:26 UTC
Labels: bug
