### ISSUE TITLE
Looks like kiwix-serve nightly has some kind of Microsoft dev lib deps

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-tools#75] opened 2017-09-10 15:38 UTC
Reported first in https://github.com/kiwix/kiwix-tools/issues/73#issuecomment-328349529

By running only kiwix-serve, the message seems to appear: "The program cannot be start because msvcr90.dll is missing."

Kind of puzzle by this situation: does that sounds normal?

**Comment by okkebal** [comment] 2017-09-18 12:49
After much 2502 and 2503 errors I finally managed to remove all versions of Redist 2008 from my computer and I only have '9.0.30729.6161" installed now both x64  and x86 versions.

Still get the error.

**Comment by kelson42** [comment] 2017-10-04 06:57
@mgautierfr Any thoughts about that. We really need to understand what goes one here.

**Comment by kelson42** [comment] 2018-01-18 13:31
We do not have forgotten about this. We anyway have to understand what is going on here as a similar problem might popup for kiwix-destktop 2.0.

**Comment by okkebal** [comment] 2018-03-13 15:10
Please take a look at this. The latest nightlies still do not work in Windows at all.

Tried on both my Windows 10 machines.

**Comment by kelson42** [comment] 2018-03-13 15:46
I have a std Windows at home, will try. Yes this is quite a problem.

**Comment by kelson42** [comment] 2018-03-15 07:54
I confirm the problem.

**Comment by kelson42** [comment] 2018-04-26 11:29
@mgautierfr I think we need to go on this with the first nightly of kiwix-desktop 2.0

**Comment by mgautierfr** [comment] 2018-08-28 16:33
I can confirm the problem. I cannot run kiwix-serve because of the missing `msvcr90.dll`.
As @okkebal, I've tried to install Visual Studio 2008 redist that should install `msvcr90.dll` but without success.
I don't know why the dll is not installed properly :/

But, I've updated our build script to use `msvcr100.dll` instead of `msvcr90.dll`.
I succeed to run `kiwix-serve`.
I have the 2017 redistribuable (x86 and x64) already installed, you will probably have to install them.

Next nightly will use `msvcr100.dll`.

**Comment by kelson42** [comment] 2018-08-29 08:32
@mgautierfr So https://download.kiwix.org/nightly/2018-08-28/kiwix-tools_win-i686-2018-08-28.zip should work?

**Comment by mgautierfr** [comment] 2018-08-29 09:29
No, it should but I forget to clean the dependency cache :/
http://download.kiwix.org/nightly/2018-08-29/kiwix-tools_win-i686-2018-08-29.zip is using `msvcr100.dll`

**Comment by kelson42** [comment] 2019-02-24 15:39
See also #261

**Comment by mgautierfr** [comment] 2019-03-04 17:38
This is another bug. I will close this issue and investigate #261.

**Closed by mgautierfr** 2019-03-04 17:38 UTC
Labels: question
