### ISSUE TITLE
kiwix-manage feature request - remove by bookid

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#228] opened 2018-09-04 13:02 UTC
It would be more convenient to be able to remove an item from library.xml by passing its bookid than its offset into an array. Alternatively, kiwix-manage show could have a switch to just return a list of bookids which could be read as an array.

**Comment by kelson42** [comment] 2018-09-04 13:15
@tim-moody Can you please give exactly what you do, what you get and what you propose?

**Comment by tim-moody** [comment] 2018-09-04 13:37
the current syntax is 

 kiwix-manage LIBRARY_PATH remove CONTENTID1 [CONTENTID2]

where CONTENTID1 ... are actually the numbers of the entries in LIBRARY_PATH

For example if kiwix-manage library.xml show gives
#7
id:             ee011249-61f1-1155-0967-7a95fd5b2bdb
path:           content/wikipedia_ne_all_novid_2017-08.zim

then wikipedia_ne_all_novid_2017-08.zim can be removed from library.xml by

kiwix-manage library.xml remove 7

I propose allowing 

kiwix-manage library.xml remove ee011249-61f1-1155-0967-7a95fd5b2bdb

**Comment by mgautierfr** [comment] 2018-09-04 13:38
There will be no array in the future. The library should be a mapping bookId->book.
The books will be addressed by their ids and only by the id.

**Comment by kelson42** [comment] 2018-09-04 13:43
@tim-moody Thx, it makes sense... kind of surprised it works with offsets... as the usage() specifically says "CONTENTID". I suspect here a regression.

**Comment by mgautierfr** [comment] 2018-09-04 13:49
No regression here, it always has been by index (since first implementation in 2011).

**Comment by tim-moody** [comment] 2018-09-04 14:01
@kelson42 was also initially surprised, given the usage statement.
@mgautierfr will you still allow multiple items on the command line with bookid?

**Comment by mgautierfr** [comment] 2018-09-04 14:03
> @mgautierfr will you still allow multiple items on the command line with bookid?

Probably, I don't see why not :)

**Comment by kelson42** [comment] 2018-09-17 05:14
@tim-moody AFAIK the fix is on its way, will take a few weeks.

**Comment by kelson42** [comment] 2018-11-01 15:31
@tim-moody This has been implemented by @mgautierfr in `kiwix-manage` 0.8 which has been released yesterday. See http://wiki.kiwix.org/wiki/OPDS#End_points. I'll close therefore the ticket. Thank you for having open it.

**Closed by kelson42** 2018-11-01 15:31 UTC
Labels: bug, enhancement

**Comment by tim-moody** [comment] 2018-11-08 18:14
@kelson42 is this really 0.8, I thought 0.7

root@box:~# /opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml.tmp remove 1
Invalid book id.
this is correct
/opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml.tmp remove 006cbd1b-16d8-b00d-a584-c1ae110a94ed
no complaints which is good
root@box:~# /opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml.tmp remove 006cbd1b-16d8-b00d-a584-c1ae110a94ed
Invalid /library/zims/content/granbluefantasy_en_all_all_nopic_2018-10.zim : error 2 opening file "/library/zims/content/granbluefantasy_en_all_all_nopic_2018-10.zim

if I remove the zim before removing it from library.xml I get error 2, which shouldn't really be an error. I think we discussed this before, but I raise it again in case it can be fixed.

**Comment by kelson42** [comment] 2018-11-08 18:19
@tim-moody Yes, 0.7, sorry

**Comment by tim-moody** [comment] 2018-11-08 18:19
/opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml.tmp remove 49d15dee-0285-77e0-64d3-e2dd524f404e 822ed684-b635-fdb1-9cd9-160f72363b1b
and
/opt/iiab/kiwix/bin/kiwix-manage /library/zims/library.xml.tmp remove "49d15dee-0285-77e0-64d3-e2dd524f404e" "822ed684-b635-fdb1-9cd9-160f72363b1b"
only remove the first item.
we discussed having this be a list as it was before, but I am OK if you don't wish to support a list. just need to know.
