### ISSUE TITLE
kiwix manage segfault on old zims

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#33] opened 2017-05-18 21:40 UTC
using nightly http://download.kiwix.org/nightly/2017-05-18/kiwix-tools_linux64_2017-05-18.tar.gz

kiwix-manage /library/zims/library.xml add /library/zims/content/ICD10-fr.zim
kiwix-manage /library/zims/library.xml add /library/zims/content/wikileaks_afghanistan_war_diary.zim

both cause segfault

others tested do not

**Comment by kelson42** [comment] 2017-05-19 07:14
Pretty sure this is a duplicate of #25

**Comment by tim-moody** [comment] 2017-05-19 12:09
possibly, but this references kiwix-manage and #25 is kiwix-serve

**Closed** 2017-05-23 15:37 UTC
Labels: bug
