### ISSUE TITLE
& symbol not redirected properly and makes additional symbols

### ISSUE THREAD

**Issue by nijazm** [kiwix/kiwix-tools#587] opened 2022-12-10 20:00 UTC
When I enter in my web browser in english wikipedia zim started by kiwix-serve symbol `&` in search and click on autocomplete result, automatically this appears in search bar `&amp;` and it goes to fulltext search, so url becomes something like this: `http://localhost:8181/search?content=wikipedia_en_all_maxi_2021-12&pattern=%26amp%3B`

However when I directly enter in url: `http://localhost:8181/wikipedia_en_all_maxi_2021-12/A/&` it redirects properly to `http://localhost:8181/wikipedia_en_all_maxi_2021-12/A/Ampersand`

I have not tested other symbols, but that reminds me of similar errors encountered on some site, where entering symbol `"` also leads to errors, causing some additional characters to appear. Is it encoding or something, I don't know. Also similar error happens in kiwix-desktop app, meaning there is no autocomplete result for `&` but only fulltext search.

**Comment by kelson42** [comment] 2022-12-10 20:11
I would wait that we support latest libzim in node-libzim and mwoffliner before investigating this. Strongly suspect this has been somehow fixed already in the libzim.

**Comment by veloman-yunkan** [comment] 2022-12-12 11:10
This issue is present (though in a slightly different way) with the new iframe-based viewer too - the fulltext search URL is `http://localhost:8181/search?content=wikipedia_en_all_maxi_2021-12&pattern=&` where the ampersand symbol in `pattern=&` is not URL encoded.

**Comment by kelson42** [comment] 2022-12-12 11:12
@veloman-yunkan OK, so at least we can fix that one.

**Comment by veloman-yunkan** [comment] 2022-12-12 11:46
BTW, the issue described in my previous comment is under Firefox 107.0. Debugging shows strange/counter-intuitive things happening, like the browser implicitly converting/decoding URLs during assignment to `innerHTML` attribute of DOM elements. I am not sure that web-browsers based on a different web-engine have the same behaviour, which may explain the issue as observed by OP.

@nijazm What is *your* browser?

**Comment by veloman-yunkan** [comment] 2022-12-12 11:46
BTW, the issue described in my previous comment is under Firefox 107.0. Debugging shows strange/counter-intuitive things happening, like the browser implicitly converting/decoding URLs during assignment to `innerHTML` attribute of DOM elements. I am not sure that web-browsers based on a different web-engine have the same behaviour, which may explain the issue as observed by OP.

@nijazm What is *your* browser?

**Comment by veloman-yunkan** [comment] 2022-12-12 12:31
A more convincing version:

```HTML
<!DOCTYPE html>
<html>
  <head>
    <script>
      function foo() { alert('ABCD%26EFGH'); }
    </script>
  </head>
  <body>
    <a href="javascript:alert('ABCD%26EFGH')">Click me!</a>
    <a href="javascript:foo()">Click me too!</a>
  </body>
</html>
```
The first hyperlink containing inline javascript in the `href` attribute displays URL-decoded text. The second hyperlink display the intended text as is.

**Comment by veloman-yunkan** [comment] 2022-12-12 12:53
A somewhat related question on stackoverflow: https://stackoverflow.com/questions/33721510/why-use-url-encoding-instead-of-html-encoding-for-the-href-attribute

**Comment by veloman-yunkan** [comment] 2022-12-15 15:13
@nijazm This should now be fixed on master but it looks like you are using the previous release of `kiwix-serve`. Is that correct? What is the output of `kiwix-serve --version` on your side?

**Comment by kelson42** [comment] 2022-12-15 15:28
To be check with latest nightly https://download.kiwix.org/nightly/

**Closed** 2022-12-15 15:28 UTC
Labels: bug, kiwix-serve

**Comment by nijazm** [comment] 2022-12-15 18:26
I just tested today's version of kiwix desktop and kiwix tools on Windows 11, and not it's even worse!
There is no search bar in kiwix serve, and on kiwix serve it is same, just shows fulltext search autocomplete result for & symbol and when I click on it in kiwix-desktop app it says No results were found for "&". Now everything is broken!

**Comment by veloman-yunkan** [comment] 2022-12-16 10:04
Now that's a different problem. Most likely, the ampersand symbol is treated as punctuation and is simply discarded during the creation of the title index as well as when running suggestion search on it.

Ideally, while building the title index we should handle article names consisting of a single symbol or word in a special way, letting those terms go into the title index as is despite any rules that drop punctuation and stopwords. Also we will have to enhance the suggestion search so that it accounts for such an addition to the title index.

@kelson42 @mgautierfr What do you think? Is this issue worth the effort required to fix it?

**Comment by kelson42** [comment] 2022-12-16 10:23
@veloman-yunkan I'm slightly lost. I would really appreciate a new ticket with a clear reproductuon case.
