### ISSUE TITLE
Possible to make Kiwix main page work with W3M terminal web browser?

### ISSUE THREAD

**Issue by gotbletu** [kiwix/kiwix-tools#583] opened 2022-11-03 21:41 UTC
Can you make the start page work with terminal web browsers?

As you can see i dont see any of my zim files to choose from when using a TUI web browser like in a GUI web browsers.
https://imgur.com/5hOAVs3.png

It does work if i know what the exact url to the zim files tho, but i usually have to open a GUI web browsers to copy the direct link, then paste in my terminal web browser, which is annoying.
https://imgur.com/04mHLEF.png
https://i.imgur.com/pNVMnQu.png

Maybe just have a generated list of links to zim files for low level web browsers aka mobile html static version

**Comment by mgautierfr** [comment] 2022-11-04 15:15
Duplicate of https://github.com/kiwix/libkiwix/issues/615

**Closed by mgautierfr** 2022-11-04 15:15 UTC

**Comment by gotbletu** [comment] 2022-11-04 17:51
Thanks for the update, not sure how hard it would be to generate basic html for those zim links but maybe one day it will work with all terminal web browsers

**Comment by kelson42** [comment] 2022-11-05 18:52
@gotbletu Not very hard like written by @gotbletu but not a priority for the moment. Would be super glad if a volunteer would take that one.

**Comment by juuz0** [comment] 2023-03-29 17:02
@gotbletu This will be in the next release (or if you want it earlier, check tomorrow's nightly release). Works in w3m browser now! :)

**Comment by gotbletu** [comment] 2023-08-12 20:40
i finally tried out the **nojs** mode, it does work to choose the zim file you want but theres no **search box** to search thru the wiki you just chosen
