### ISSUE TITLE
zimdump fails due to filename too long

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-tools#644] opened 2023-11-01 08:24 UTC
I get this error while trying to zimdump a zimit file:
```
Error writing file to errors dir. /data/www.banrepcultural.org_769ad4f0/_exceptions/A%2fvalidate.perfdrive.com%2f?ssa=035a3c4d-bb78-4882-ac0d-37b12acd74cd&ssb=69300321024&ssc=https%3A%2F%2Fwww.banrepcultural.org%2Fimpresiones-de-un-viaje%2Findex.php%3Fr%3Dvocabulario%252Findex%26letra%3DC&ssi=28869177-c583-4c9d-be25-4c224c6b0d11&ssk=support@shieldsquare.com&ssm=333017385496800083316227533760233&ssn=c151313584265281406987e1e088c5d7b7c1f3d48df9-b03f-4541-842607&sso=2cafa86a-73dee8c7fbb24077335045ed4086e0a464f1743d519afcad&ssp=37219467071698734226169876154209029&ssq=64283268046825621338080051117365935547176&ssr=MTM1LjE4MS4xODEuOTc=&sst=Mozilla%2f5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit%2f605.1.15%20(KHTML,%20like%20Gecko)%20Version%2f17.0%20Safari%2f605.1.15%20Youzim.it+%20contact+zimfarm@kiwix.org&ssu=&ssv=&ssw=&ssx=eyJfX3V6bWYiOiI3ZjYwMDBjZjgwNzI4YS1mNGE0LTQyNjUtOTY0OC1lY2IwZTE3MmFkMGExNjk4NzgwMDUxMTIyNDE3MDgyLTE3YjJkY2YyMGU1ZWZhMDAzMzEifQ==
Exception: Error writing file to errors dir. /data/www.banrepcultural.org_769ad4f0/_exceptions/A%2fvalidate.perfdrive.com%2f?ssa=035a3c4d-bb78-4882-ac0d-37b12acd74cd&ssb=69300321024&ssc=https%3A%2F%2Fwww.banrepcultural.org%2Fimpresiones-de-un-viaje%2Findex.php%3Fr%3Dvocabulario%252Findex%26letra%3DC&ssi=28869177-c583-4c9d-be25-4c224c6b0d11&ssk=support@shieldsquare.com&ssm=333017385496800083316227533760233&ssn=c151313584265281406987e1e088c5d7b7c1f3d48df9-b03f-4541-842607&sso=2cafa86a-73dee8c7fbb24077335045ed4086e0a464f1743d519afcad&ssp=37219467071698734226169876154209029&ssq=64283268046825621338080051117365935547176&ssr=MTM1LjE4MS4xODEuOTc=&sst=Mozilla%2f5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit%2f605.1.15%20(KHTML,%20like%20Gecko)%20Version%2f17.0%20Safari%2f605.1.15%20Youzim.it+%20contact+zimfarm@kiwix.org&ssu=&ssv=&ssw=&ssx=eyJfX3V6bWYiOiI3ZjYwMDBjZjgwNzI4YS1mNGE0LTQyNjUtOTY0OC1lY2IwZTE3MmFkMGExNjk4NzgwMDUxMTIyNDE3MDgyLTE3YjJkY2YyMGU1ZWZhMDAzMzEifQ==
```

This is due to filename being too long for my filesystem.

Is there a flag to ask to not stop/fail on such error, or a flag to truncate filenames ? This file is already an exception and in current situation I do not care much about its content, but I would like to be able to extract other files.

**Comment by mgautierfr** [comment] 2023-11-01 08:55
Duplicate of https://github.com/openzim/zim-tools/issues/213

**Closed by mgautierfr** 2023-11-01 08:55 UTC
Labels: question

**Comment by benoit74** [comment] 2023-11-01 08:56
(and wrong repo obviously ... the reason why I did not find the issue ^^)
