### ISSUE TITLE
Kiwix issue with expanding article sections

### ISSUE THREAD

**Issue by shotintoeternity** [kiwix/kiwix-tools#339] opened 2019-10-02 12:42 UTC
Categories are not expanding properly when clicked or touched in Kiwix on the below platforms;

Windows (x64)
Android
Linux
iOS

When selecting a category, the categories are not expanding using Chrome or Safari as browsers. The issue is also occurring on the Android app as per the bug here:  https://github.com/kiwix/kiwix-android/issues/1064

![kiwix](https://user-images.githubusercontent.com/266741/66044830-6936e500-e4f0-11e9-9852-084aaefec25a.jpg)

Any help would be greatly appreciated as this seems to be a severe issue dramatically impacting users' ability to access articles. Thanks!

**Comment by kelson42** [comment] 2019-10-02 18:53
@rgaudin This file is broken, like probably all the other done around that time. Could you please refresh it/them?

**Comment by kelson42** [comment] 2019-10-03 08:03
The root cause problem was https://github.com/openzim/mwoffliner/issues/633 or really similar.

**Comment by rgaudin** [comment] 2019-10-03 10:35
I'm not sure this is related to that issue as the issue clearly mentions `1.8.1` with a fix on `1.8.3`.
We don't have any runs with `1.8.1`, `1.8.2` nor `1.8.3` on the zimfarm.

I have relaunched [wikipedia_tl_all](https://farm.openzim.org/tasks/5d95c2ccefd26e8d5d6a602d) so you can check but if this is fixed and we need to relaunch some ZIMs, we'll need a list of this (or criteria to find it).

**Comment by kelson42** [comment] 2019-10-03 15:22
@shotintoeternity A new version of that ZIM files has been generated here https://download.kiwix.org/zim/wikipedia/wikipedia_tl_all_maxi_2019-10.zim and the problem should be fixed. Please let us know if you are aware about other files having a similar problem.

**Closed by kelson42** 2019-10-03 15:22 UTC
Labels: bug, question

**Comment by shotintoeternity** [comment] 2019-10-05 10:36
Thank you everyone!
