### ISSUE TITLE
Accesing offline higher definition version of images in zim

### ISSUE THREAD

**Issue by zkosk** [kiwix/kiwix-tools#437] opened 2021-02-28 08:11 UTC
In wikipedia_en_all_maxi.zim, images are very blurred and not clickable, this make images with text hard to read (example: the Direct_Rendering_Manager page). How to view a higher definition version of the image without accessing online resources? Can the higher definition version  be packaged as an additional optional zim which is referenced by kiwix-serve.exe?

Some possible options to reduce the size of this package:

1. Partition between topic groups depending on which topic contains a lot of image.
2. Automatically idendify which images have text, then build a package that contains higher definition version of images with text inside or use HD version for images with text by default.

**Comment by kelson42** [comment] 2021-03-04 08:12
Basically a duplicate of https://github.com/openzim/mwoffliner/issues/1404

**Closed** 2021-03-04 08:12 UTC
Labels: duplicate, enhancement
