### ISSUE TITLE
Kiwix-serve serves every resource with illegal characters appended

### ISSUE THREAD

**Issue by JonathanJonathanJonathan** [kiwix/kiwix-tools#151] opened 2018-01-24 15:50 UTC
![image](https://user-images.githubusercontent.com/934563/35340849-857d3b1c-0124-11e8-957b-80668890b6e3.png)
![image](https://user-images.githubusercontent.com/934563/35340896-a3aef936-0124-11e8-8218-7861b54743b0.png)

As you can see there are \u0 characters appended. Also the HTML files have strange characters appended. 
Due to that the jquery is not functioning and all the pages are broken. It's not the ZIM file itself since the error also occurs in the library overview.

Hope you guys can help me out :) 

Running debian 8.9 on a https://www.pcengines.ch/apu3a2.htm

**Comment by mgautierfr** [comment] 2018-01-24 16:00
Which version of kiwix-serve are you using ?

It is probably a duplicate of https://github.com/kiwix/kiwix-tools/issues/15

**Comment by JonathanJonathanJonathan** [comment] 2018-01-24 16:05
@mgautierfr thanks for your fast reply! Using the one from the frontpage (https://download.kiwix.org/bin/kiwix-linux-x86_64.tar.bz2) However that one unpacked shows files that are dating from 2014... So I think you're right, now trying to deploy the https://download.kiwix.org/bin/0.10/ version!

**Comment by kelson42** [comment] 2018-01-24 16:14
@JonathanJonathanJonathan better use a nightly https://download.kiwix.org/nightly/

**Comment by JonathanJonathanJonathan** [comment] 2018-01-24 17:11
@kelson42 & @mgautierfr thanks a lot! It resolved all the problems.

**Comment by kelson42** [comment] 2018-01-24 18:44
:)

**Closed by kelson42** 2018-01-24 18:44 UTC
