### ISSUE TITLE
iframe defaults to height: 150px; in older browsers

### ISSUE THREAD

**Issue by tim78245** [kiwix/kiwix-tools#592] opened 2023-01-01 04:55 UTC
Using an [older browser](https://www.seamonkey-project.org/) the iframe that serves the content is only set to 150px high, making the content difficult to read.

This works:
<iframe src="http://en.wikipedia.org" style="height:100%;width:100%;"></iframe>

This does not:
<iframe src="http://en.wikipedia.org"></iframe>

However there is something in the kiwix webpage that doesn't work when I try appending height:100% to the iframe element. I don't know why.

**Comment by kelson42** [comment] 2023-01-01 08:32
@tim78245 Which exact version of seamonkey do you use? We need to reproduce the bug first.

**Comment by kelson42** [comment] 2023-01-01 08:41
This CSS spec is interesting https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-height

**Comment by tim78245** [comment] 2023-01-01 18:27
> @tim78245 Which exact version of seamonkey do you use? We need to reproduce the bug first.

the current version, 2.53.14.

> This CSS spec is interesting https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-height

Yes, 150px is the default.

**Comment by kelson42** [comment] 2023-01-31 06:49
@veloman-yunkan Could you please make this quick fix?

**Comment by veloman-yunkan** [comment] 2023-02-07 09:55
#871 made the situation for seamonkey even worse (see https://github.com/kiwix/libkiwix/pull/871#issuecomment-1420485032). I will try to make seamonkey happy with kiwix-serve's ZIM viewer again.

**Comment by veloman-yunkan** [comment] 2023-02-07 09:59
Regarding the wrong height of the iframe - the root cause is because seamonkey doesn't recognize `window.visualViewport`:

> ```
> TypeError: window.visualViewport is undefined[Learn More]  viewer.js:187:3
>	handle_visual_viewport_change http://localhost:8080/ROOT/skin/viewer.js:187:3
> ```

**Comment by kelson42** [comment] 2023-02-07 10:37
@veloman-yunkan So, it's a WONTFIX? Uers have to use a recent browser?

**Comment by veloman-yunkan** [comment] 2023-02-07 13:26
> @veloman-yunkan So, it's a WONTFIX? Uers have to use a recent browser?

No. I have already fixed (or rather worked around) the issue reported in this ticket, but it won't make any difference until kiwix/libkiwix#885 is fixed too (which I am working on now).

**Closed** 2023-02-08 14:42 UTC
Labels: bug, kiwix-serve
