### ISSUE TITLE
formatting tags in search results

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-tools#125] opened 2017-12-04 18:54 UTC
to reproduce view http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_2017-11.zim in
http://download.kiwix.org/nightly/2017-12-01/kiwix-tools_armhf_2017-12-01.tar.gz

search for pneumonia

results include <i>Pneumocystis</i> pneumonia where <i> are the italics.

**Comment by kelson42** [comment] 2017-12-04 18:59
Duplicate of https://github.com/openzim/mwoffliner/issues/159.

**Closed by kelson42** 2017-12-04 18:59 UTC
